import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "@/app/globals.css";
import Logo from "@/public/assets/logo/Vector.png"

const inter = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fast Change",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: '(prefers-color-scheme: light)',
        url: '@/public/assets/logo/Vector.png',
        href: '@/public/assets/logo/Vector.png',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
